### ISSUE TITLE
Adapt OA `is_closed_archivable` variable

### ISSUE THREAD

**Issue by delwen** [maia-sh/intovalue-data#12]
https://github.com/maia-sh/intovalue-data/blob/d4a57fa8cd298c2c2f2f58f0cb6e428c603f58a1/scripts/15_prepare-trials.R#L381

- NAs currently don't distinguish between (a) closed pubs for which we couldn't get a self-archiving permission; (b) open access pubs (for which this indeed doesn't apply).
- Need to re-think levels

**Comment by maia-sh** [comment]
What's the next action on this issue?
