### ISSUE TITLE
Update readme with latest decision on summary results reporting in DRKS

### ISSUE THREAD

**Issue by delwen** [maia-sh/intovalue-data#15]
Update decision on summary results in DRKS: an automated search was used to find summary results in DRKS using pre-defined keywords (e.g., Ergebnisbericht, Abschlussbericht) in the relevant registry section. The date of summary results posting in DRKS was determined through manual inspection of the registry’s change history (reflects upload).

**Comment by maia-sh** [comment]
Fixed in https://github.com/maia-sh/intovalue-data/commit/d8fe94200aa0f53467531999015b643e0b38f7c0
