### ISSUE TITLE
Update OA data

### ISSUE THREAD

**Issue by maia-sh** [maia-sh/intovalue-data#29]
👋  @delwen !

I updated the registry data in https://github.com/maia-sh/intovalue-data/tree/update-tv-decisions and will get out of the branch now. If you could check it out and update the oa data, and then trials.csv/rds, that would be super. then pr the branch and we can use it in tv.
note: i got two 2 new pubmed records but the rest still use the version from 2021-08-15; maybe we can update those, but not worth the time right now.

**Comment by delwen** [comment]
:wave: @maia-sh!

Done! Updated the Unpaywall and SYP data and re-generated trials.csv/rds. Not sure I understood what you meant about the 2 new PubMed records and the rest using the 2021-08-15 version. Wasn't the registry data also updated?
