### ISSUE TITLE
Update registry data for dashboard

### ISSUE THREAD

**Issue by maia-sh** [maia-sh/intovalue-data#34]
👋 @delwen !

Per our decision to update the data for the dashboard, I started a branch: [update-2022-november](https://github.com/maia-sh/intovalue-data/tree/update-2022-november).

I ran scripts 6-10, and pushed the resulting higher-level files (not raw/processed). Now the OA from you, and we can create the updated trials.csv.

Also, we should decide where to store the raw data, both for this and April 2022 updates, and future such updates. Perhaps updating [https://zenodo.org/record/6560383](https://zenodo.org/record/6560383)? Let's discuss.

**Comment by delwen** [comment]
thanks @maia-sh! OK I will run scripts 12-13 (OA) and then script 14 to create the final CSVs.

Should we create a new release for this updated version?

Re raw data: yes, I think updating the Zenodo dataset would be a good option. Let's discuss further.

**Comment by delwen** [comment]
@maia-sh I ran the OA and SYP update (scripts 12/13) and reverted the log file to that in main to avoid merge conflicts. After merging, I'll change the log file directly in main. TODO: we need a better system for this going forwards.

Could you run script 14 for the final dataset?

Could you also update the registry data for the updated cohort for prospective registration in CT.gov?

Thanks!
