### ISSUE TITLE
Edit `publication_type` for trials with non-journal article dois

### ISSUE THREAD

**Issue by maia-sh** [maia-sh/intovalue-data#6]
@delwen found some trials with publications marked as journal publications with dois but which did not resolve in unpaywall. however, some are broken dois or other publication_type.

```
intovalue %>% 
  filter(
    has_publication,
    publication_type == "journal publication",
    !is.na(doi)
  ) %>% 
  filter(is.na(color))
```

@delwen is going to do some replacements, similar to https://github.com/maia-sh/intovalue-data/blob/main/R/04_prepare-data.R#L60

**Comment by delwen** [comment]
I'm thinking of incorporating the replacements directly into https://github.com/maia-sh/intovalue-data/blob/main/R/04_prepare-data.R. Alternatively we could have it as a dashboard-specific change. Thoughts?

**Comment by maia-sh** [comment]
in prepare data sounds good to me!

**Comment by maia-sh** [comment]
Circling back to this. Did you make some changes in a branch? Lost the thread here. Also, there are several branches - could you delete whatever is merged/deprecated?

**Comment by delwen** [comment]
Just submitted a PR for this!

Other deprecated branches also now deleted.
